export var list_song = [
    {
        id: '1',
        title: 'Cao ốc 20',
        artist: 'Masew',
        album: 'rap',
        url: './src/music/Cao-oc-20.mp3',
        avt: './src/images/avt_music/music_1.png',
        time: '03:51',
    },
    {
        id: '2',
        title: 'Lần cuối',
        artist: 'Karik',
        time: '02:44',
        album: 'Rap',
        url: './src/music/Lan_cuoi.mp3',
        avt: './src/images/avt_music/music_2.jpg',
    },
    {
        id: '3',
        title: 'cơm đoàn viên',
        artist: 'Thành Đạt',
        time: '04:41',
        album: 'Rap',
        url: './src/music/Com-doan-vien.mp3',
        avt: './src/images/avt_music/music_3.jpg',
    },
    {
        id: '4',
        title: 'phía sau tờ đô la',
        artist: 'Cao Tùng Anh',
        time: '05:00',
        album: 'Rap',
        url: './src/music/Phia-sau-to-do-la.mp3',
        avt: './src/images/avt_music/music_4.avif',
    },
    {
        id: '5',
        title: 'Nhớ gia đình',
        artist: 'Lê Bảo Bình',
        time: '04:46',
        album: 'Rap',
        url: './src/music/Nho-gia-dinh.mp3',
        avt: './src/images/avt_music/music_5.jpg',
    },
    {
        id: '6',
        title: 'Con trai cưng',
        artist: 'BRay',
        time: '03:18',
        album: 'Rap',
        url: './src/music/Con-trai-cung.mp3',
        avt: './src/images/avt_music/music_6.jpg',
    },
    {
        id: '7',
        title: 'Khóc một mình',
        artist: 'Karik',
        time: '03:52',
        album: 'Rap',
        url: './src/music/Khoc-mot-minh.mp3',
        avt: './src/images/avt_music/music_7.jpg',
    },
    {
        id: '8',
        title: 'Nhớ gia đình',
        artist: 'Lê Bảo Bình',
        time: '04:46',
        album: 'Rap',
        url: './src/music/Nho-gia-dinh.mp3',
        avt: './src/images/avt_music/music_8.jpg',
    },
    {
        id: '9',
        title: 'Con trai cưng',
        artist: 'BRay',
        time: '03:18',
        album: 'Rap',
        url: './src/music/Con-trai-cung.mp3',
        avt: './src/images/avt_music/music_9.jpg',
    },


];

export var genresData = [
    {
        id: '1',
        title: 'Nhạc rap',
        number_tracks: '120',
        avt: './src/images/avt_genre/avt_1.jpg',
    },
    {
        id: '2',
        title: 'Nhạc trẻ',
        number_tracks: '120',
        avt: './src/images/avt_genre/avt_2.jpg',
    },
    {
        id: '3',
        title: 'Nhạc trữ tình',
        number_tracks: '120',
        avt: './src/images/avt_genre/avt_3.jpg',
    },
    {
        id: '4',
        title: 'Nhạc chill',
        number_tracks: '120',
        avt: './src/images/avt_genre/avt_4.jpg',
    },
    {
        id: '5',
        title: 'Nhạc EMD',
        number_tracks: '120',
        avt: './src/images/avt_genre/avt_5.jpg',
    },
]

